Project.MVCUI/Controllers/LoginController.cs
using Project.BLL.DesignPatterns.GenericRepository.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class LoginController : Controller
    {

        AppUserRepository _apRep;

        public LoginController()
        {
            _apRep=new AppUserRepository();
        }


        
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(AppUser appUser)
        {
            AppUser user = _apRep.FirstOfDefault(x => x.UserName == appUser.UserName);
            if (user==null)
            {
                ViewBag.ZatenVar = "Kullanıcı ismi daha önce alınmıs";
                return View();
            }

            string decrypted=Crypt.Encrypt(appUser.Password);
            
            if (user.Password==decrypted&&user.Role==ENTITIES.Enums.UserRole.Admin)
            {
                Session["admin"] = user;
                return RedirectToAction("AppUserList", "AppUser", new { Area = "Administration" });
            }
            else if(user.Password==decrypted&&user.Role==ENTITIES.Enums.UserRole.BranchManager)
            {
                Session["manager"]=user;
                return RedirectToAction("AppUserList", "AppUser", new { Area = "Administration" });
            }
            else if (user.Password == decrypted && user.Role ==ENTITIES.Enums.UserRole.SalesRepresentative)
            {
                Session["sales"] = user;
                return RedirectToAction("ProductList", "Product", new { Area = "Administration" });
            }
            else if (user.Password == decrypted && user.Role ==ENTITIES.Enums.UserRole.AccountingRepresentative)
            {
                Session["account"] = user;
                return RedirectToAction("ExpenseList", "Expense", new { Area = "Administration" });
            }
            else if (user.Password == decrypted && user.Role ==ENTITIES.Enums.UserRole.WarehouseRepresentative)
            {
                Session["ware"] = user;
                return RedirectToAction("ProductList", "Product", new { Area = "Administration" });

            }
            else if (user.Password == decrypted && user.Role ==ENTITIES.Enums.UserRole.TechnicalServiceRepresentative)
            {
                Session["technical"] = user;
                return RedirectToAction("IssueList", "Issue", new { Area = "Administration" });
            }
            else if (user.Password == decrypted && user.Role ==ENTITIES.Enums.UserRole.MobileSalesRepresentative)
            {
                Session["mobileSales"] = user;
                return RedirectToAction("ProductList","Product", new { Area = "Administration" });

            }
            else if (user.Password == decrypted && user.Role ==ENTITIES.Enums.UserRole.Member)
            {
                if (!user.Active)
                {
                    return AktifKontrol();
                }

                Session["member"] = user;
                return RedirectToAction("ShoppingList", "Shopping");
            }
            ViewBag.ZatenVar = "Kullanıcı yok";
            return View();
         
        }
        public ActionResult LogOut()
        {
            Session.Clear();
            return RedirectToAction("Login", "Login");

        }
        public ActionResult AktifKontrol()
        {
            ViewBag.AktifDegil = "Hesabiniz aktif degil";
            return View("Login");
        }

    }
}

Project.MVCUI/Controllers/RegisterController.cs
using Project.BLL.DesignPatterns.GenericRepository.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using Project.MVCUI.VMClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class RegisterController : Controller
    {
        AppUserRepository _apRep;
        AppUserProfileRepository _apUserProfile;

        public RegisterController()
        {
            _apRep = new AppUserRepository();
            _apUserProfile = new AppUserProfileRepository();
        }
        public ActionResult RegisterNow()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterNow(AppUserVM apvm)  
        {
            AppUser user = apvm.AppUser;
            AppUserProfile profile = apvm.Profile;

            user.Password = Crypt.Encrypt(user.Password);//sifreyi kriptoladık
            user.ConfirmPassword = Crypt.Encrypt(user.Password);

            if (_apRep.Any(x=>x.UserName==user.UserName))
            {
                ViewBag.ZatenVar ="Kullanıcı ismi daha önce alınmıs";
                return View();
            }
            else if (_apRep.Any(x=>x.Email==user.Email))
            {
                ViewBag.ZatenVar= "Email zaten kayıtlı";
                return View();
            }
            //Kullanıcı basarılı bir şekilde register işlemini tamamladıysa ona mail gönder...
            string gonderilecekEmail = "Tebrikler...Hesabınız olusturulmustur...Hesabınızı aktive etmek https://localhost:44350/Register/Activation/" + user.ActivationCode + " linkine tıklayabilirsiniz";
            MailService.Send(user.Email,body: gonderilecekEmail,subject: "Hesap AKtivasyon!!!");
            _apRep.Add(user);
            if (!string.IsNullOrEmpty(profile.FirstName)& ! string.IsNullOrEmpty(profile.LastName)&!string.IsNullOrEmpty(profile.Address)&!string.IsNullOrEmpty(profile.TCNO))
            {
                profile.ID = user.ID;
                _apUserProfile.Add(profile);
            }
            return View("RegisterOK");

            
        }
        public ActionResult Activation(Guid id)
        {
            AppUser aktifEdilecek = _apRep.FirstOfDefault(x => x.ActivationCode == id);
            if (aktifEdilecek!=null)
            {
                aktifEdilecek.Active = true;
                _apRep.Update(aktifEdilecek);
                TempData["HesapAktif"]= "Hesabınız aktif hale getirildi";
                return RedirectToAction("Login", "Login");
            }
            //Supheli bir aktivite
            TempData["HesapAktifMi"]= "Hesabınız bulunamadı";
            return RedirectToAction("Login", "Login");
        }
        public ActionResult RegisterOK()
        {
            return View();
        }



        

    }
}

Project.MVCUI/Views/Login/Login.cshtml
@model AppUserVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="YZL3157">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>RegisterNow</title>

    <link href="~/OuterTools/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/OuterTools/css/bootstrap-reset.css" rel="stylesheet" />
    <link href="~/OuterTools/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/OuterTools/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="~/OuterTools/css/owl.carousel.css" type="text/css">
    <!-- Custom styles for this template -->
    <link href="~/OuterTools/css/style.css" rel="stylesheet">
    <link href="~/OuterTools/css/style-responsive.css" rel="stylesheet" />

</head>
<body class="login-body">
    <div class="container">





        @using (Html.BeginForm("Login", "Login", FormMethod.Post, new { @class = "form-signin" }))
        {


            <br /> <center><h2>Giriş Yapınız</h2></center>

            <center> <h5 style="color:red">@TempData["HesapAktifMi"]    @ViewBag.ZatenVar</h5>        </center>
            <div class="login-wrap">
                @Html.TextBoxFor(x => x.AppUser.UserName, new { @class = "form-control", placeholder = "Kullanıcı ismi belirleyin" })
                @Html.PasswordFor(x => x.AppUser.Password, new { @class = "form-control", placeholder = "Sifre belirleyin" })




                <br />

                <button class="btn btn-primary">Giriş Yap</button>

                <div>
                    @Html.ActionLink("Kayıt Ol", "RegisterNow", "Register")
                </div>

            </div>

        }



    </div>
</body>
</html>